version: '3.8'

services:
  mqtt:
    build:
      context: .
      dockerfile: docker/mosquitto/Dockerfile
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto:/mosquitto/config
    networks:
      - fabric_test
    restart: always

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: coldchain
      POSTGRES_USER: diana
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fabric_test
    restart: always

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/coldchain
      SPRING_DATASOURCE_USERNAME: diana
      SPRING_DATASOURCE_PASSWORD: secret
      MQTT_BROKER_URI: tcp://mqtt:1883
    volumes:
      - /Users/computadora/coldchain-prototipo/fabric/network:/fabric-network
    networks:
      - fabric_test
    depends_on:
      - postgres
      - mqtt
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fabric_test
    restart: always

volumes:
  pgdata:
    driver: local

networks:
  fabric_test:
    external: true
