spring.application.name=backend


spring.datasource.username=diana
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
server.port=8080
# MQTT broker para backend dentro de Docker:
mqtt.broker.uri=tcp://mqtt:1883

# PostgreSQL dentro de Docker:
spring.datasource.url=jdbc:postgresql://postgres:5432/coldchain

# --- Fabric Gateway Config ---
fabric.channel.name=mychannel
fabric.chaincode.name=chaincode-temp
fabric.msp.id=Org1MSP
fabric.peer.endpoint=peer0.org1.example.com:7051
fabric.peer.hostOverride=peer0.org1.example.com
fabric.tls.caCertPath=/fabric-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
fabric.user.certPath=/fabric-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem
fabric.user.keyDir=/fabric-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore
fabric.gateway.discovery=true
